### ISSUE TITLE
Expressions of Interest: Talks and Workshops

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#1]
Talks, content, workshops, panels, etc.  I should clarify that this issue is for gathering interest from people want to help gather content.  This group of people will be responsible for creating a "Call for Content" mechanism and open review process for the event :)

If you have a talk suggestion, then you might need to bide your time a little...

**Comment by KoryNunn** [comment]
Edit: Didn't read good. Happy to help though.

**Comment by SomeoneWeird** [comment]
*raises hand to help run things*

**Comment by timoxley** [comment]
I'll put my hand up for this, one thing I like to believe we've done well with at CampJS is the content.

I think we should do an anonymised CFP with the help from the diversity group, form a panel and then vote to gen an initial round of talks. Historically, the CFP produces only a small percentage of the talks that end up happening, most simply come through people approaching me or me approaching people.

I really liked the idea of dual presenters from CampJS III but not many people took it seriously.

**Comment by MauriceButler** [comment]
Happy to help as well.

**Comment by MauriceButler** [comment]
Should we start asking for content suggestions sooner rather than later?

Also possibly register with some aggregators to attract international speakers?

something like https://calltospeakers.com/  (https://twitter.com/calltospeakers)

**Comment by DamonOehlman** [comment]
I think getting in early with content suggestions make sense, but I'd defer to Tim's judgement on using an aggregator.  I know that because we endeavour to keep the costs of CampJS down, and sponsorship dollars are traditionally very hard fought we do need to be careful about blowing the budget on too many international speakers.

**Comment by DamonOehlman** [comment]
A quick update is that we have a date confirmed for the event (see issue linked above) so I've gone ahead and created a Lanyrd event page for things.  Not sure if you folks want to use Lanyrd for managing Call for Speakers, etc, but they seem to offer that facility now.

Anyway, event page is here:

http://lanyrd.com/2015/campjsnews/

I've issued a claim for the event page (after creating it) so should be able to add other admin type people soon hopefully...

**Comment by SomeoneWeird** [comment]
We should probably start a CFP ASAP.

**Comment by DamonOehlman** [comment]
@SomeoneWeird @MauriceButler @timoxley Just checking in on this to see how folks are going?  Tim - I know you've had a process in the past and are keen to lead this effort, so maybe you want to point the folks in the right direction?

**Comment by timoxley** [comment]
In the past I've set up a google form, then evaluate entries while also chasing down people I think will provide good content. Next I try to chat to each presenter about what type of stuff they're going to do so there's some cohesiveness about the camp. Note that most of the past CampJS content hasn't come at all from the CFP and submission numbers have historically been very low e.g. ~10-20.

**Comment by timoxley** [comment]
Sadly, I'm probably going to have to bow out of organising this at all though  :cry:

**Comment by MauriceButler** [comment]
Plenty of locals / regulars could be relied on, have been thinking of possible OS speakers not actually approached yet.

Probably depends on budget / sponsorships but I assume the incentive is come to australia and hang out with cool people. And possibly we could cover travel funds permitting?

**Comment by timoxley** [comment]
We've done well in the past with "send speakers" as a form of sponsorship, have particularly appreciated this type of support from Mozilla, but important to note that AU companies typically want to sponsor a lot less than international companies and it's important to get sponsorship money from them along with the speaker.

**Comment by DamonOehlman** [comment]
@timoxley yep, you'll be missed, but with a wedding to plan it's completely understood.

@MauriceButler @SomeoneWeird I'm happy to help out here as well, but it would be good to have someone driving this.  Are one of you happy to do this?

I'm keen for a good showing from locals, and I'll investigate options for seeing if there are any sponsors that are keen to send out a speaker also.

**Comment by timoxley** [comment]
Because we run only 6 month in advance it's harder to lock sponsorships down before lining up the international speakers. Also sponsors can be very slow to reach an agreement with, or they'll do things like drop out two weeks before the event leaving us over ten thousand dollars short of the predicted budget, which comes out of my pocket… Good times.

Normally what I do is just try make an awesome lineup with 2 – 3 international guests then pray the sponsorships will cover it by the end. Not sure if the praying is part of my process you want to replicate though.

**Comment by MauriceButler** [comment]
I really want to see this thing come together but like most am time poor atm...

In lieu of any other option in site I will run with it as much as I can but would love / need as much support as possible.

I would much prefer to lock in at least some tickets / sponsorship first so we know we can actually put on a decent camp but both of those things are harder without a speaker list.

Did any tickets get pre sold at the end of last camp? If so thats a start?

On the book them in and pray option...

If we do take this approach and things do fall through should we work out in advance how this is going to be covered? Otherwise we might end up in a spot of bother withing nobody willing to step up.

https://twitter.com/needadebitcard possibly...

**Comment by DamonOehlman** [comment]
OK, let's go with a content first approach for this Camp, being mindful of what resources we are strong on around the Brisbane / Gold Coast region.  For example, with a really strong contingent of nodebot folks it would be great to engage that community again (although they might be a bit worn out from previous camps).

Maybe we could do node rockets ;)

**Comment by DamonOehlman** [comment]
Will tweet #8 to help us determine popular content (if it works that is).

**Comment by MauriceButler** [comment]
Very good. Ill start asking around a bit more aggressively.

**Comment by SomeoneWeird** [comment]
I can ask around, but not sure how much time I can dedicate over the next couple weeks unfortunately - oversees for work :(

**Comment by DamonOehlman** [comment]
Preliminary call stuff added to lanyrd:

http://lanyrd.com/2015/campjsnews/calls/qdbgk/

Which leads to this form:

http://goo.gl/forms/3xensRuz2u

@SomeoneWeird @MauriceButler you both have editing access to fix any typos or wording that I've added that you think is either incorrect or sends the wrong message :)
