### ISSUE TITLE
Networking Crew

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#10]
@SomeoneWeird to take the reigns on pulling this one together - thanks Adam!

**Comment by SomeoneWeird** [comment]
We have a few things at our disposal: 
- 3x UniFi Pros
- ~200m of cat6 cable 
- Mikrotik routerboard
- Gigabyte Brix box

ping @deoxxa @eugeneware @mipearson (if any of you guys don't want to help/aren't coming just let me know)

And for anyone else who has networking experience, your help would be extremely appreciated :tada:

**Comment by DamonOehlman** [comment]
@MauriceButler do you think you'll be able to drag @liamoehlman along this year?

**Comment by MauriceButler** [comment]
Again I maybe talking out of school but I recall we permanently installed / left a bunch of gear over the last few camps at Koonjewarre.

Is that included in the above list?

**Comment by KoryNunn** [comment]
We've been constantly trying to get @liamoehlman to go, with no result.

**Comment by MauriceButler** [comment]
@DamonOehlman He is right here beside me whinging about having to leave his room on a weekend... Ill do my best though and I am sure if we can get him there he will help out to the best of his ability.

**Comment by SomeoneWeird** [comment]
I'm not sure if we ended up leaving anything at Koonjewarre, they do have pre-existing non-pro unifis around the place, though. We wired in our own as extras last time.

**Comment by mipearson** [comment]
Not sure whether I'll be going - will get back to y'all. Team's gotten pretty big so sending everybody isn't as easy as it used to be :)

Koonjewarre has (had?) non-5ghz UniFI APs that were drastically underpowered for handling camp volumes. I think I may have managed to break the configuration of one of the APs last time I was there :(

**Comment by deoxxa** [comment]
I'm down to clown!

**Comment by geoffreyd** [comment]
Yeah, the UniFi's we installed, I'm pretty sure are still there, They will be good for reaching the far corners, but we'll have to mix them with our own stuff for the main group areas ... probably some Airport Extremes.

Also the cable we ran across from the main hall to the second building must be getting pretty close to it's end of life, being that it was an indoor cable installed very much in the wild outdoors.

**Comment by DamonOehlman** [comment]
@geoffreyd I can probably get some outdoor cable sourced easily enough (Dad is a TV tech, used to do aerial installations, etc).  Just not sure how much before the event I'll be in the area, but looking to be there a day or two before with the family for a holiday if the timing works out :)

**Comment by SomeoneWeird** [comment]
Yep. We still have 3 UniFi Pros in our possession, and a _lot_ of cat5/6(?) cable that we can hook up too.

**Comment by DamonOehlman** [comment]
Just had a phone conversation with Jeff Lynne @digitalcraft (who is currently minding the networking stuff the Digital8 office in BNE).  He's more than happy to help out with doing some network config at the event and also bring some additional gear.

Will bring:
- The CampJS networkinging stash (UniFis, network cable, etc)

Can bring:
- A server to host something like [dokku](https://github.com/progrium/dokku) and a suitable downstream NPM proxy, perhaps [sinopia](https://github.com/rlidwka/sinopia).
- Power boards (do we have these, are they normally provided by the venue?)  Can make contact with Koonjewarre if needed
- Other things we might need...

Thanks heaps to Jeff for offering to help out!

**Comment by MauriceButler** [comment]
:tada: Yay for Jeff!

**Comment by SomeoneWeird** [comment]
Ok, awesome. Re powerboards, we had a lottt of them last time and iirc somebody bought them along

**Comment by digitalcraft** [comment]
That was me. I picked the up from Nigel in a suitcase, and I still have them. 30-40 perhaps.
I will do up an inventory this weekend.

I have a bunch of HP micro servers which I am no longer using. I have no problems with donating these to CampJS. They are not hugely powerful. But they are portable and decent.

I will report back this weekend to see how Dokku goes on them.

**Comment by DamonOehlman** [comment]
Thanks Jeff - really appreciate your help :)

**Comment by SomeoneWeird** [comment]
Awesome. We also have a fairly beefy gigabyte box that a mentioned elsewhere in this thread, but having more would be fantastic :)

**Comment by digitalcraft** [comment]
Does anyone know where this Gigabyte box would be?

So far I have proxy setup and AP's.
I see there is an intranet branch from last year.

So I'm thinking intranet + npm repository on Gigabyte brix.

**Comment by SomeoneWeird** [comment]
Yeah, I have it at home. I don't get back into the country until Wednesday though :(

**Comment by digitalcraft** [comment]
All good. I have a mac-mini thats spare right now.

**Comment by DamonOehlman** [comment]
@digitalcraft @porty a massive thanks from both @SomeoneWeird and myself for all your work, and everyone else who came along to the event.  Really appreciated everything :)
