### ISSUE TITLE
Transport Crew

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#11]
We need to have some people who are excellent at coordinating things, to help organise transport to and from the venue from Gold Coast Airport.  Looking for volunteers but already know how good @iamkevinv is at crossing t's and dotting i's so wondering whether there'd be interest there?

**Comment by timoxley** [comment]
I'd like to second the nomination @iamkevinv.

**Comment by iamkevinv** [comment]
Me? Timely and organised? You sure about that? haha.
I can certainly be pedantic though so if that's what you were after, all
good. :)

**Comment by garrows** [comment]
I would also like to vote for @iamkevinv :P

**Comment by DamonOehlman** [comment]
Motion carried.

**Comment by SomeoneWeird** [comment]
This is totally up to him, remember guys :P

**Comment by iamkevinv** [comment]
I feel like saying <ackbar>it's a trap</ackbar> but it's almost too obvious.
Okay so what's entailed here based on past experience?

**Comment by MauriceButler** [comment]
Hey @iamkevinv I don't know exactly but I would assume.
- Collation of attendees and when / how they are arriving (google spreadsheet worked last time?)
- Organisation of the bus hire to and from the venue to suit those times / numbers (Brisbane Bus lines maybe?)
- Delegation of rounding up people at pick-up points to ensure everyone is accounted for.
- Possibly waking everyone up on the Monday morning to ensure everyone who needs to gets on a bus.

**Comment by DamonOehlman** [comment]
@timoxley Which bus company have you used in the past?  I can probably make contact soon to get a quote, etc and start getting things moving for organising the buses and hand over to @iamkevinv for the more fine grained logistics if Kev agrees to take it on :)

**Comment by timoxley** [comment]
> Which bus company have you used in the past?

@DamonOehlman Murray's. One thing to note if looking at other bus companies is that they may or may not be aware of the few treacherous sections of road going up to the camp and need to be made aware. I believe there were issues with one campjs/railscamp and the bus had to turn around and go "the long way" which is an additional hour or so of slow, snaking travel.

**Comment by DamonOehlman** [comment]
Thanks Tim - that was one of the reasons I asked.  If one of existing vendors are familiar with the road then I'm happy to stick with them :)

**Comment by timoxley** [comment]
I suggest getting a few quotes anyway and pitting them against each other for a good price.

**Comment by DamonOehlman** [comment]
:cagematch: (should be an emoji for this)

**Comment by iamkevinv** [comment]
Right so i figured i'd pipe in here and say that i've been super smashed at work, so this has fallen off my radar. As i've been so kindly volunteered in for this - i guess i'd better do it otherwise it will become a big issue real fast. @timoxley if you have any prior documentation, contact numbers or methods that worked in the past, please pass them along as soon as you can - i'm sure it will help launch me forward. 

Pickup is from Coolangatta airport as well as the Bearded Dragon pub or something? I never actually took the bus except for Melbourne CampJS's - so i'm just trying to catch up here. I'll review and collate the mentions of the travel plans from the public facing emails tim has sent in the past as part of plan b.

**Comment by SomeoneWeird** [comment]
If stuff has come up and you're not able to help - I'm sure we can find someone else.

In the past we've given a list of attendees (incl their phone numbers) that have indicated that they want transport by bus. Usually everyone meets up at the bar in the airport (there's only 1, in the middle). Coolangatta is very small, there's only 2 bus places, one at each end of the airport. Last time the bus swung by the train station so we could pick everyone who caught the train up, and this time we'll probably go to a bottleo before heading to the camp. 

cc/ @DamonOehlman

**Comment by iamkevinv** [comment]
Okay cool. That also helps. I'm busy yes - but many are, so i guess having a deputy will be helpful. I'd still really like to contribute as i've always said.

**Comment by DamonOehlman** [comment]
@iamkevinv all good mate, I'm handling getting the quotes and sorting all that out, but if you are able to help on the day that would be awesome.  It's pretty close to locked down now too :)

**Comment by iamkevinv** [comment]
OH! Well i'm relieved it's been so well handled but also disappointed i haven't been around to give you a hand in that case. No problem with being the transport contact. Send me all the details you have and i'll make sure i'm all over it :)

**Comment by iamkevinv** [comment]
Okay so i'm going to assume we'll need a survey sent to everyone to express their interest in getting an airport transfer, Their name, their phone number (critical), their flight number (can check if they are delayed which was an issue on the melb one), which pickup point they will be at, and which bus (2pm or 5pm) they want. I wanted to whip up some sort of check-in phone app for this purpose but i'll never have time with the hours i currently work. 
A separate booking for the return journey should be made on that survey also.
...thoughts?

**Comment by DamonOehlman** [comment]
@iamkevinv Yep good point - I've got a logistics survey started so I'll invite you to that and maybe you can build out that section :)

**Comment by DamonOehlman** [comment]
I've added those questions Kev - thanks for the extra detail :)

**Comment by DamonOehlman** [comment]
Survey goes out in the morning - so we'll start collecting info.

**Comment by iamkevinv** [comment]
Mate, sorry about that, i didn't see your messages at all. I work all of teh hourz right now - blocking out other things. Glad i was able to give you the info though - that will help a lot.

So i can probably drive down to the airport for the first bus if you like so i can help herd humans as planned. Not sure if i'll stop off at the venue, drop off my stuff, then drive out south again....but at some point i can burn rubber to the airport.

Did i need to be there for bus2? or have we arranged a deputy who is a bus2 person? I mean, i can spend the whole afternoon driving, but i'd probably need to refuel at least once haha. 
Thoughts on how to handle this are appreciated.

**Comment by MauriceButler** [comment]
Nominating a deputy on each flight / time slot would mean you dont have to be there. That has worked in the past.

Once all the surveys are in then have a look for someone that might be willing to be a beacon and hit them up.

**Comment by iamkevinv** [comment]
I'll find the invite to the surveys. Need to feel organised. ;-)

**Comment by DamonOehlman** [comment]
:)  @SomeoneWeird has volunteered to be the beacon for the 2pm bus.  And the 5pm bus had very few people so I've been talking to people who indicated a preference for catching that bus and working towards getting them in Uber's up to the campsite instead.  Will let you know more on that soon.

**Comment by iamkevinv** [comment]
Ah awesome that saves me going back and forth a few times with a few pit
stops for fuel.
I'll check off attendance of those getting off the bus perhaps - to ensure
nobody was left behind and we have to order some uber for them.
I'll easily be able to direct people into busses and check off attendance
on each for those departing Monday.

**Comment by SomeoneWeird** [comment]
Yeah that would be great :)

**Comment by iamkevinv** [comment]
@DamonOehlman How did the ubers for latecomers go? I've downloaded a fresh survey set and filtered on those who said 'yes' on the making use of bus. @SomeoneWeird - Did you need a copy to be on the same page?

**Comment by SomeoneWeird** [comment]
Hm I've got a list too, but would be great if you could send me yours too just so I can cross check - adam@boxxen.org

Cya tomorrow :)

**Comment by iamkevinv** [comment]
It is done.

**Comment by DamonOehlman** [comment]
@iamkevinv thanks for helping get everyone to and from the camp :)
