### ISSUE TITLE
Beverages Crew

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#12]
Looking for some good people to help ensure that we have appropriate beverages for the event.
- Water
- Coffee
- Soft drinks (Soda Stream for laughs maybe?)
- Juice poppers
- Flavoured Milk (apparently a crowd favourite)
- Beer
- Wine

All items to be consumed in a responsible fashion.  Yes, even the water.

**Comment by SomeoneWeird** [comment]
I think we need softdrinks, at a minimum?

**Comment by DamonOehlman** [comment]
Historically, we have always had alcohol included in the ticket price of the event.  We could consider this year having more of a BYO flavour though so those who aren't drinking don't feel like they are subsidising others drinking though.  Also, we do want to make this event feel more "everybody friendly" and alcohol has sometimes been working against this.

I don't really have an opinion but know it has been raised previously...

Thoughts?

**Comment by DamonOehlman** [comment]
@SomeoneWeird good call, edited.

**Comment by MauriceButler** [comment]
Just to put into the right issue as stated in #4 I am working on obtaining some sponsorship / assistance from "large liquor chain". No guarantee yet but Ill update with more info as I have it.

**Comment by MauriceButler** [comment]
Additionally I have been pledged $500 from an anonymous donor so that can be added to the budget.

**Comment by KoryNunn** [comment]
I don't mind the idea of splitting attendance into BYO and Drinks tickets, since the consumption seems to vary quite a lot between attendees. Removing included drinks entirely would drastically change the vibe of CampJS, in my opinion, for the worse.

**Comment by DamonOehlman** [comment]
Thanks @MauriceButler and @KoryNunn - I agree that the "just turn up" beauty of CampJS would take a hit if we didn't include drinks, especially given a lot of people travel from interstate.  I think the overheads of attempting to police "BYO" from "paid drinks" tickets would be a nightmare, so I think we should just keep things as they are.

Any issues that arise from consumption of alcohol to excess can be dealt with by a more direct approach, as long as someone is happy to do it (and I guess I'll put my hand up for that).

**Comment by SomeoneWeird** [comment]
It might be worth having a "help pay for drinks" ticket that is $xx more than a regular ticket, even if people who are drinking don't buy it, some will, and it will help more?

**Comment by rvagg** [comment]
I like that idea @SomeoneWeird but that may call into play some perverse incentives, [this famous experiment](http://freakonomics.com/2013/10/23/what-makes-people-do-what-they-do/) suggests that we may be asking people to think of themselves as entitled to drink more if they pay extra.

There be dragons in social engineering.

**Comment by MauriceButler** [comment]
I agree with @rvagg the unintended result may outway the benefit of such a ticket. 

A similar approach might beat the end of camp there is an option to donate some money (anonymously?) to be used to make the next camp better.

This very well may be plagued by the same issues though.

**Comment by DamonOehlman** [comment]
I think the correct action in this case is to take no action.  Let's leave it as is and remind people that we are an environment that encourages relaxing and having a good time, but if your behaviour causes someone else to not have a good time then we'll be dealing with that.  Editing the topic description to remove separation between the items...

**Comment by DamonOehlman** [comment]
@MauriceButler you happy to keep an eye on this one then?

**Comment by MauriceButler** [comment]
Yep I am being very careful not to spread myself too thin but Yes I will keep pushing my possible sponsorship angle and update this space.

**Comment by SomeoneWeird** [comment]
@rvagg ah yes I didn't even think about that :)

**Comment by geoffreyd** [comment]
One of the things we learned pretty early on was that having plenty of non Alcoholic drinks went down well. Soft drinks sure, but we've never been able to have enough juice poppers.

**Comment by SomeoneWeird** [comment]
The flavoured milk was appreciated too, especially by @joshgillies

https://twitter.com/AliciaBatman/status/601697746064572418

**Comment by DamonOehlman** [comment]
I'll update the description again :)

**Comment by joshgillies** [comment]
Flavoured milk would be greatly appreciated! :)

**Comment by tjstebbing** [comment]
random thoughts:
- The milks and the gingerbeer was a spur of the moment thing, they were there at aldi, I grabbed them and they went really fast. 
- My diversity panel last campJS spurred some really good conversation about alcohol, I'm not going to repeat all of it as it was a non-recorded session but some of the items were important to consider. Suggestion of having a company provide a porta-bar where people could buy drinks was popular because a) it would reduce non-drinking attendee's ticket price fairly substantially, b) they would handle age issues etc. Another point raised was that it would make the event more young-people-friendly (less peer pressure to drink )
- Last campJS I arranged a barista for the weekend, this was rather popular.

**Comment by mipearson** [comment]
Re #2: As soon as you take money for alcohol things become a lot more complicated.

**Comment by mipearson** [comment]
Also - now that the expectation has been established, not offering alcoholic drinks as part of the ticket would kill attendance.

**Comment by MauriceButler** [comment]
I kind of agree that the expectation has been established but maybe it can be achieved differently. 

A combination of a couple of the above ideas. 

Attendence Tickets are $X
Alcohol armbands are $Y

X + Y being roughly existing ticket price. 

Have a bar for alcholic drinks but rather than a cash bar, armbands are required and is same as current system. 

This means tickets to the event are cheaper, and non drinkers are not subsidising. 

Also allows enforcement of the 18+ via armband same as concerts etc thus opens up the younger attendees. 

Thus hopefully would circumvent the social issues with entitlement etc. As have to have a band to drink and is no different to any other event.

**Comment by todthomson** [comment]
@MauriceButler :+1: great idea

**Comment by timoxley** [comment]
> armbands are required

Who polices this?

> now that the expectation has been established

This expectation might be stronger in those who have attended railscamps.

> not offering alcoholic drinks as part of the ticket would kill attendance.

It may also attract different people, could even increase attendance.

> it would reduce non-drinking attendee's ticket price fairly substantially

I have a feeling it won't reduce ticket price that much… perhaps 10% – 15%.

**Comment by KoryNunn** [comment]
Some issues I can see with the bar-style ticket system:
- Armbands would need to be reallocated daily as they get destroyed by activities/showers etc..
- Nothing stops arm-banders grabbing drinks for non-arm-banders (thus reducing supply for non-sharing arm-banders)

I reckon either leave drinks in (since the vast majority of attendees make use) or make it BYO (but that hurts people travelling)

**Comment by mipearson** [comment]
Bowing out here. A "community brainstorm" is not a productive way to arrange something this complicated.

**Comment by timoxley** [comment]
I suggest defer decision to diversity team.

**Comment by DamonOehlman** [comment]
@timoxley :+1: Also, I think @mipearson has a good point here also, so I'll start a doc somewhere and open it up for comment for the diversity team.  I'll also try to make sure that the diversity team is represented with a fair cross section of existing participants and those we would like to engage in a better way.

**Comment by DamonOehlman** [comment]
As mentioned in #15 the event will be BYO until we get some clear information on what ability we have to legally and responsibly supply alcohol at the event.  Some docs I have found and am currently perusing:
- https://publications.qld.gov.au/storage/f/2014-06-20T05%3A14%3A01.993Z/information-for-community-groups.pdf (QLD)
- https://publications.qld.gov.au/storage/f/2014-06-17T02%3A12%3A15.110Z/form-7-application-for-a-community-liquor-permit.pdf (Community Liquor License Application - QLD) - license cost - $61.05 per day, so roughly $180 for Fri - Sun.
- http://www.nfplaw.org.au/sites/default/files/Events_involving_alcohol_0_0_0.pdf (NSW)

**Comment by davekinkead** [comment]
Understand we have to play by any govt rules but I for one am very sad to see this move to BYO.  

One of the things that made CampJS special (for me at least) was the open & inclusive nature of not just people but organisation & pricing.  The event itself mirrored the best bits of OSS - everything was in-commons, nothing was transaction.  

Now there will be mine & yours... did I bring enough ... where's the nearest bottlo ... is anyone going into town soon ... hey, who took my Asahi :(

**Comment by DamonOehlman** [comment]
Thanks Dave - I agree, the mine and yours thing is something I really want to avoid.  I know that your voice is in line with quite a few others so if we put our heads together I reckon we can probably come up with something.

```
/me puts on thinking cap
```

**Comment by DamonOehlman** [comment]
Closing this to encourage more positive (i.e. making the decision right) conversation in #17

**Comment by DamonOehlman** [comment]
Also, just so everyone is aware I have made contact with Liquor and Gaming folks (from my personal email) with some "I've got a friend who is running an event" questions to get some concrete information on this issue.  This includes what our duties are as an event in our current BYO case also.
