### ISSUE TITLE
Association Registration

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#14]
Just had a quick look at the paperwork and it doesn't look too scary to formalise the creation of an association (at least in NSW):

https://ablis.business.gov.au/nsw/Resource/AP4550.pdf

Had a seriously quick skim over the [Fair Trading Model Constitution](http://www.fairtrading.nsw.gov.au/docs/Cooperatives_and_associations/Model_constitution.rtf) in all it's RTF glory and nothing seemed too scary.  My gut is leaning towards us doing this prior to the next event so we can ensure Tim and Wei's financial sanity.

If there is general agreement on doing this, then I'll perhaps create an "association" repo and get the ball rolling...

**Comment by DamonOehlman** [comment]
Also, keeping it at two events a year we should remain under the $150K level for Non-profits having to register for GST (see: https://www.ato.gov.au/Non-profit/Your-organisation/GST/)

The more I read, the less scary this is seeming....

**Comment by DamonOehlman** [comment]
Also, association fees: 

http://www.fairtrading.nsw.gov.au/ftw/About_us/Our_services/Fees/Associations_fees.page

Looks like registration is probably less that $200 (need to pay both the registration and reservation of name costs I think).

**Comment by SomeoneWeird** [comment]
This could be a good idea. Dinner time but I'll read through stuff when i get back :+1:

**Comment by SomeoneWeird** [comment]
@pomke suggested we try becoming a sub-committee for LCA
https://www.linux.org.au/sub-committees

**Comment by tjstebbing** [comment]
pycon-au has done this very successfully for a while now, have a chat with Richard Jones who set it up afaik, he's a pretty cool dude, I'm sure he'd be happy to chat about it. From memory the benefits are:
- get a bank account
- get insurance cover
- potential for funding

cons:
- tied to LCA, have to abide by their sub-committee policy
- LCA itself has an open membership, some people in the LUG community are pretty trolly (this shouldnt impact a sub-committee but really.. these people keep me from being overly involved in LCA)

**Comment by DamonOehlman** [comment]
@pomke @SomeoneWeird definitely something we should be open to, though I expect we will choose to go our own way in the longer term.  If it was something that was a good fit though I'd be pretty keen.  I know a few people already involved with LCA and those people have always been nice enough to deal with :)

I'll have a bit of a dig around regarding what's involved from the insurance side.  I'm not too worried about Bank accounts and financial entities, etc, but if insurance requirements and cost overheads are high then... well, I'd be putting in a strong vote to come under an existing umbrella of another association and LCA sounds ideal.

**Comment by SomeoneWeird** [comment]
For sure, other than that, I'm all for getting something set up, and am down for helping longer term.

**Comment by mipearson** [comment]
> LCA

Hsssssssssss.

**Comment by MauriceButler** [comment]
Long term being our own association would be best but time frames, insurance, etc might make it hard to be ready in time for this camp?

If we can pull it off great but we really are up against it time wise

**Comment by AnnaGerber** [comment]
I was involved in incorporating an association (Brismesh Inc) in QLD in 2003. Getting a bank account and insurance are things that an Incorporated association can do anyway without being part of an umbrella group.

The hardest part of the paperwork was drafting the constitution (ie. rules), and it that case it involved many hours of drafting and editing, which we tried to do as a group but unfortunately these kinds of activities bring out the pedants and trolls (not that I'm saying that would happen with this community). There are model rules that can be used as a template to save everyone a bunch of work and unpleasantness.

Be aware that becoming an incorporated association comes with all kinds of overheads (having a formalised management structure & the associated community politics that go along with that, following rules about notice periods and quorum for meetings, keeping minutes for general members meetings, management meetings and AGMs, submitting financial paperwork, etc). At times it is time-consuming boring, and frustrating work (IMO) and there is a danger that one or two people can get burnt out unless everyone is aware of this and willing to pitch in.

**Comment by DamonOehlman** [comment]
Thanks Anna.  You were involved with Brismesh - awesome!  I got close to getting involved with that, but never did :)

I'm happy to take on some of the administrative burden as long as there are a couple of willing other participants.  I really do feel like we've outgrown our current "just a group of people" structure.  This is most evident when we get to the point of collecting sponsorship dollars.  It was quite awkward directing companies to a link that an account that was associated with Tim's name when they had signed up to sponsor CampJS.  This was the thing that really brought it home for me anyway...

Without wanting to offend the fine people that run my son's soccer club, my thoughts are if they can manage it we most definitely can.

**Comment by mipearson** [comment]
Please have a chat to the people involved in Ruby Australia.

During the AGM at the RailsCamp they mentioned that they've had to learn the hard way on a lot of these hurdles and were more than willing to share their experience with other organisations wishing to do the same.

**Comment by DamonOehlman** [comment]
Yep, I've previously chatted to @freshtonic about getting in touch with them prior to the last CampJS.  Any tips on who to talk to?

**Comment by SomeoneWeird** [comment]
@melissakaulfuss HI

**Comment by MelissaKaulfuss** [comment]
hi?

**Comment by SomeoneWeird** [comment]
@MelissaKaulfuss haha sorry, do you have any experience with what Ruby Australia has done with regards to rubyconf and setting up a NFP?

**Comment by MelissaKaulfuss** [comment]
No, it was Keith Pitty, I just spoke with Matta, you just need to speak
with an accountant apparently.
Along the lines of what Ben Schwarz said the other day.

**Comment by freshtonic** [comment]
@DamonOehlman Keith Pitty is the man to talk to. Do you guys need an introduction?

**Comment by DamonOehlman** [comment]
@freshtonic @MelissaKaulfuss We've met IRL once before for DuckJS, so I'll DM Keith and get a conversation started.  Thanks for the lead.

**Comment by freshtonic** [comment]
DuckJS is the answer to everything

**Comment by DamonOehlman** [comment]
Just by way of an update, I feel like it might be ok for me to manage through a personal bank account (already have one that is nicely isolated) given what I have read here:

https://www.ourcommunity.com.au/management/view_help_sheet.do?articleid=2101

This might be a good way to ensure we can get ticket sales cranking along now.

**Comment by DamonOehlman** [comment]
An email exchange with my accountant (names changed to protect the innocent) for those that are interested.

My questions:

> Hey Rufus the Amazing Accountant,
> 
> Just wondering if I can get a bit of advice regarding the overheads of registering and running a not-for-profit association.  I've been involved with a professional community group for quite some time which hosts a bi-annual retreat.  For the last 5 events one of the organisers has managed all the funds through his own personal account, which I suspect has been made simpler because he currently lives in Singapore and probably does his financial reporting there.
> 
> It is, however, I think time to take the next step and get something more formal together so we have proper financial channels (i.e. a bank account) through which to receive and pay monies.
> 
> From having a look at the NSW fair trading docs, the process looks reasonably simple and additionally from a tax law point of view it seems that if the associations annual revenue is less that $150K it doesn't need to register for GST (which would be ideal).
> 
> Just wondering if you had any experience with this kind of thing (in QLD, or NSW I guess) and whether it is something you would recommend having an accountant involved with?  If it is worth getting an accountant involved, is it best to do that from the setup or at close out of the first financial year?
> 
> Hope everything is continuing to go well up there!
> 
> Cheers,
> Damon.

Accountant's response:

> Hi Damon,
> 
> Should be okay to do the admin yourself.
> 
> In Qld need an Accountant to sign off on a review each year if turnover/assets > $20,000 and < $100,000.  This Accountant need not be in practice.
> 
> If > than $100,000 than need an Auditor and this is more serious and will need formal accounts and someone in practice.  Could cost around $1,000 to audit.
> 
> Under $20,000 is a sign off from the President/Treasurer.  So hope your under that!
> 
> Not sure of rules in NSW.
> 
> Good luck.
> 
> Regards,
> Rufus.

As previously mentioned in other issues, we won't be getting the association setup prior to CampJS VI but I'd like to make sure we make our best effort to get this sorted at the next event!

**Comment by DamonOehlman** [comment]
Just for people's information, some progress is being made towards this by @twalve and @JedWatson (with input from @timoxley and others).  The scope of the organisation has grown beyond just CampJS and the intention now is to create an entity that covers all not-for-profit JS events in Australia.  Something like "JS Australia".  Closing this here for now, I would expect more news in the coming month or two.
