### ISSUE TITLE
State of the Nation - Where are we at now?

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#15]
Morning All,

Just wanted to provide a brief overview of where we are at with regards to CampJS VI.  Some of this is concrete and some of it is also my opinion:
## FACTS
- Koonjewarre is booked in for the 20 - 23 November (hooray).
- I've done some cost modelling for the camp in this [drive sheet](https://docs.google.com/spreadsheets/d/1OxeFbpou22IrWcTS4ZMN--Wq8TywzPODVZkshfg4Dgs/edit#gid=0).  Reasonably happy with where it is at.
- We need to resolve financial channels (i.e. bank account) for the upcoming event.  Previously, Tim has managed this through his own accounts and it's not really OK for one person to wear this amount of financial risk.
## OPINIONS
- Strongly leaning towards going through the process of registering an independent association for CampJS to ensure our values as a community are ours to control.  Some background and discussion here: #14.  Primary reason for this is to provide us a way to handle the finances.
- The upcoming event will likely be a BYO alcohol affair, and we will work out some kind of system for helping our interstate travellers acquire desired beverages on the way to the location.  This is primarily due to risks to the proposed association serving alcohol without a license, but does also represent an experiment in the way we run CampJS.
- There will be one ticket price (current estimate based on modelling - $330).  No sales, no discounts, just the lowest possible price for everybody.  While Tim raised some [good points about human behaviour](https://github.com/campjs/campjs-vi/issues/7#issuecomment-132699804) I'm hoping we can use some other techniques to help promote sales.
- Some of our baseline costs should always be allocated to assisting with travel expenses / and-or travel expenses.  This is a point of difference from other events, and I think it's a good one.  We have received some constructive criticism in the past about the individuals that have been brought out in the past, and some of that has been fair (though in these instances costs have been mainly covered through sponsorship).  What I am proposing is the inclusion of $4000 in the baseline budget that will assist to help bring people that couldn't otherwise make the event to attend.  The process for determining how this money is spent is still to be determined.
- We will have "stretch goals" for the upcoming camp.  Based on the cost modelling I have done, we break even with 80 attendees.  After that we start being able to contribute to those stretch goals.  At the moment I have included a coffee cart + barista in the stretch goals with a cost estimate and also think we should further contribute to our 4K travel fund allotment after that a little too.  Other ideas are very welcome.
## QUESTIONS / ANSWERS

Based on all of the above, you may have some questions.  I've attempted to guess some of these and provide answers in advance (below).  For those that I have missed, feel free to ask in this issue and I'll do my best to answer them:
1. _The proposed ticket prices for CampJS VI is quite a bit less that the ticket prices was for CampJS V.  Is this because alcohol is no longer included in the ticket price?_
   
   It does contribute but it's not the main reason for the price difference.  The primary differentiator in cost is cost overheads for the venue.  We love Lord Somers as a venue but it is a bit more pricey than Koonjewarre.  The actual percentage cost of alcohol against the total cost for the event for CampJS V was roughly 5%, so by not including alcohol I guess we all get a 5% discount, but just have to work out how to get stuff there ourselves.
   
   We don't have headroom for special ticket prices though, so remember you are getting the best possible deal when you purchase your ticket.
2. _Would removing the "Travel / Attendance Subsidies" from the baseline costs, bring the ticket price down further._
   
   Yes, it probably would... **but**, I personally feel very strongly that this is what makes CampJS such an interesting event.  It's also taking advantage of the economies of scale.  For example, consider if every one of us was going to fly and stay somewhere outside of Australia to attend a conference of the standard of CampJS.  How much would that actually cost?  What CampJS has always tried to do, and I wholeheartedly believe it to be a good thing is to bring interesting people out here to visit.  It just makes sense, and we are going to continue to do this as a community.  We are, however, going to be transparent with the costs and the 4K represents what I believe to be the minimum require to preserve the essence of CampJS.  Let's hit those stretch goals though to try and make it a bigger deal though!
3. _What is your quest?_
   
   To find the... um, sorry, to ensure that what Tim and a few others started with the vision for CampJS gets a really good run at CampJS VI and we ensure that Tim and Wei get to enjoy their wedding without losing any sleep over the event.

**Comment by timoxley** [comment]
CampJS might be able to cash in on the fact that jsconf.asia is happening just prior to campjs – perhaps we could drag some of their speakers over the water to CampJS during the same trip.

**Comment by MauriceButler** [comment]
@timoxley I have been looking at what other conferences are around the same time and trying to work out how to approach speakers on short notice.

Do you have a contact there that might be inclined to let us "borrow" their speaker list?
