### ISSUE TITLE
Tickets are on Sale (August Early Bird - $330) !!!

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#16]
Evening All,

OK - Tickets are on sale.  I've decided to park the association registration prior to CampJS VI, but will have some paperwork with me at the event so we can get the ball rolling there and migrate from an "unincorporated association" into an "incorporated association".

But that's all pretty boring. Much more exciting is that you can now purchase CampJS VI tickets through the following link:

https://www.tickettailor.com/checkout/view-event/id/33392/chk/ac9b/

I ended up going through a service called "Ticket Tailor" instead of ti.to for event registration.  While I'm a big fan of ti.to it was obvious during the cost modelling how much a hit ti.to's 3% processing fee has on our bottom line.  Ticket Tailor charge $25USD per month, but have no commissions so we are only paying for the payment provider processing fees (30c + 1.75% per transaction).

I've tested the process by purchasing the first ticket to the event and the flow works well enough.  I guess we'll see who get's in with ticket #2 soon enough ;)

Cheers,
Damon.

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by SomeoneWeird** [comment]
One of the guys over at Pin Payment have said they're willing to help with card processing fees, it would probably require us implementing something on the website but [pins payment buttons](https://pin.net.au/docs/guides/payment-buttons) don't look bad and probably wouldn't take too long. Will look into it more in the next couple of days when I get a chance.

**Comment by DamonOehlman** [comment]
That would be great.  I'm currently using Stripe just because I had it previously connected to the isolated account that I'll use to handle finances for CampJS VI.  I'll get the same account authorized with the pin account that I set up so we can switch across pronto if its a good fit.

**Comment by DamonOehlman** [comment]
Hmmm, a bit of a roadblock on pin setup (account username: damon@campjs.com) as the financial information setup requires an ABN and CampJS does not have one.  To do the finances for the camp, the account name on the pin account will probably have to be something like:

"Damon Oehlman as trustee for CampJS VI"

**Comment by timoxley** [comment]
> While I'm a big fan of ti.to it was obvious during the cost modelling how much a hit ti.to's 3% processing fee has on our bottom line

This is a shame, I feel some degree of loyalty to tito since we've been using them for CampJS since before they'd opened their doors to the public IIRC. If you have any problems with this new mob please note that tito always provided prompt support whenever there were issues and have even incorporated our feedback into their application e.g. their pin integration was added specifically at our request.

**Comment by rvagg** [comment]
really nice experience with the new ticket purchasing system, +1 from me

**Comment by DamonOehlman** [comment]
@timoxley yeah, I liked the ti.to experience too (had used them for organising Nodebots SYD last year also).  I wasn't aware that the pin integration had been added at our request that is definitely a nice feature, but super impressed that they did that.

I have to say though It really hit home once I started incorporating the ticket processing fees in the budget calculation sheet how much those processing fees add up.  Even at $330 x 80 tickets, its about $800 vs $75 for 3 months of ticket tailor.  Unfortunately I'm a horribly dispassionate person when it comes to spending a :dollar:  (i.e. very little brand loyalty).

**Comment by xzyfer** [comment]
@DamonOehlman we've previously been able to secure ti.to sponsorship for previous community events in the form of lower transaction fees. This could be an avenue worth pursuing.

**Comment by DamonOehlman** [comment]
@xzyfer thanks for the tip - I'll get in touch with them and have a chat about this.

**Comment by DamonOehlman** [comment]
ti.to folks were excellent, we'll definitely talk to them again for doing the CampJS VII tickets (I don't think we should switch from ticket tailor now for VI unless there is a problem).  Also they are going to look at getting some of their unwritten policies for how they do currently support community events more visible so this can be easily discovered by community event organisers :)

**Comment by DamonOehlman** [comment]
Reckon we well and truly announce this.  Closing.
