### ISSUE TITLE
Making BYO work

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#17]
Hey folks,

I know this has been a big change for everyone, but as an individual whose name is going to be tied to the organisation and finances for this event I was not comfortable with the legal and/or social impact for supplying alcohol at CampJS VI.  Any legal ramifications for mismanagement of supplied alcohol at the event would have impacted me personally, and thus my wife and kids too.  This isn't something that I think any individual or family should take on.  I know Tim has done this in the past, but now that our Tim is growing up and getting married to the lovely Wei, I think even he is going to think twice about doing this in the future.

I'm sure you'll all agree that it's the environment, excellent talks and general community vibe that make CampJS awesome.  Sure in some cases a drink or two helps that along, and bringing alcohol along is fine.  I don't think not supplying alcohol is going to wreck things.  We may have to manage a few extra things, so people don't feel like they have to hire a full-time guard to protect their portion of trappist beer but I think we'll do a top job.   Heck, there's a chance  that by not supplying alcohol at the event, more people will feel ok about attending.  Again, this is isn't the reason alcohol won't be supplied this time round, but it's probably an A/B test worth conducting.

If anyone has constructive ideas on how to make BYO work at the event - feel free to leave them here.  If us not supplying alcohol means that CampJS isn't for you, then we'll definitely miss you but that's that way things are going to be for this event.   Once there is an association (see #14) then we will revisit this decision, but for now, this has to be my decision given potential liability issues - feel free to email me (damon@campjs.com) but if you are just having a whinge then you may not get a response.

Cheers,
Damon.

**Comment by iamkevinv** [comment]
In due time, I just want to know where the cost saving of beer/wine will instead be spent. Because the early bird ticket i just bought didn't get cheaper (that's fine) and my heart wants to know it went to worthy replacement goodness.

**Comment by DamonOehlman** [comment]
Sure thing Kev - some of that is covered in #15 and I'll happy to answer any additional questions (feel free to email me if you'd prefer - damon@campjs.com).  The financial modelling I have done is all available [here](https://docs.google.com/spreadsheets/d/1OxeFbpou22IrWcTS4ZMN--Wq8TywzPODVZkshfg4Dgs/edit#gid=0) for review and commenting as a few people have already done (originally linked in the Budget issue).

One of the primary differences is that I'm pretty sure that Tim sold the early, early, early bird tickets as what I would call a "loss leader".  To ensure we remain in the black for this event (and future events) I felt it was important that even at the lowest ticket price should ensure we break even based on an estimated attendance. I factored this on 80 people, which is conservative, but I was also factoring in some potential attrition due to the changes I knew I needed to make regarding alcohol.  Also worth noting is that the calculations I have made do not include sponsorship $$$ as these things are highly variable.

All being well we will hit ~110 people as per normal, land lots of good sponsors, and have $$$ left in the kitty to do some extra nice swag for this event.  That's the plan anyway :)

**Comment by iamkevinv** [comment]
Nice :+1:

**Comment by lukebrooker** [comment]
Just a quick idea on BYO. Would there be enough fridge space to give each BYO attendee a single row (front to back) in the fridge and have boxes of those coloured dot (or company) stickers and you put one on each of your drinks (maybe even with your initials or 'tag' :wink:)?

I'd only bring a six pack or two, but it would be nice to have room for at least a few at a time in the fridge. The stickers also _might_ deter people grabbing others drinks without someone noticing.

Anyway, only idea I have come up with so far, but I thought the sticker thing might be somewhat fun/creative. Feel free to tell me the horrible ways it could go wrong :smile:

**Comment by hackling** [comment]
So tonight I learned that campJS was going to be BYO this year. A friend told me, I disbelieved him, but could neither confirm or deny this information by looking at the campJS website. He then directed me to look for the github repo and check out the issues.

As someone who has been to a number of Railscamps, and a couple campJS as well, I kind of just assumed that booze was provided. I've even brought up the fact when explaining the camp to people I want to encourage to come along. BYO camps aren't exactly the norm in my experience and I'm sure I won't be the only person to make this assumption.

I've made the mistake of taking my own booze to the first camp I went to an it really wasn't required as there was plenty to go around. As a result, I haven't done it since. 

I think one of the key things to make BYO work is to make sure that people are informed about it. Perhaps update the website, send out an email to ticket holders. I'd hate to be one of people who didn't find out though and rock up empty handed, and the location of the camp makes it a non-trivial task to pop down to the bottle-o.

**Comment by hackling** [comment]
Another suggestion along the lines of getting BYO to work:

Maybe encourage attendees to pool together and collectively sort out their alcohol needs.
If a bunch of people all pool together and buy the same kind of beer, than a lot issues with the fridge space is going to be solved as you won't have 80 people trying to put 80 different kinds of drinks in the fridge. 

It'll also help avoid feel bads when someone gets their drinks pinched etc, or there is a mix up as to who's is who's.

Another way to solve the fridge issue is to encourage people to bring their own eskys and maybe the camp could help provide ice over the weekend.

**Comment by DamonOehlman** [comment]
@hackling Yep, it was double-takes all round when I first announced that for this camp.  Apologies for the lack of info on the website, I'll see if I can we can put some information somewhere...

I think the idea of people pooling is a great idea, and would definitely encourage that.  Not sure how to help organise that but if you think of something let me know.  Additionally, to help manage things I've actually organised to have a whole pile of stickers printed off so you can clearly mark your beer, cider, as yours which hopefully limits confusion during the event.

Also, now that the people are all starting to finally get their tickets sorted, I'll be moving to emailing just those people that have a ticket and one of the key items for early next week (or the week after possibly) will be something focused on logistics around alcohol.  Definitely happy to source ice for the entire weekend if people are thinking of bringing eskies.   I've organised a big cool room thingy from a hire place so we should be able to keep it frozen over the weekend without too much difficulty.

**Comment by hughsk** [comment]
Any chance of the bus stopping by a bottle shop on the way to the camp for those of us flying in? Not essential by any means, but I wouldn't mind having a few ciders over the weekend :)

**Comment by DamonOehlman** [comment]
Yep - see #19 (there's a stopped planned at Dan Murphy's Robina for each of the inbound to CampJS transfer buses).

In the email I'm going to send out re alcohol, I'll be encouraging folks to do a pay online collect in-store kind of thing to try and keep the trip pretty snappy :)

**Comment by lukebrooker** [comment]
@DamonOehlman If you need help with organising the drinks setup at the camp, I'd be happy to help.

**Comment by hackling** [comment]
It's worth noting that Dan Murphy's offers free delivery on orders over $300.

**Comment by DamonOehlman** [comment]
I think it's definitely worth someone getting in touch with Dan Murphy's to see if we can get a code that allows us to combine personal orders together for a batched delivery that would be awesome.  I can probably do this at some point, but if you are offering @lukebrooker that would be fantastic!

As much as I'd like to send a spreadsheet round asking for people's orders and batching it all up into a single order, I'm fairly certain (there's only so many hypothetical questions my "friend" can ask the QLD Office of Liquor and Gaming Regulation) that would still be considered centralizing the supply of the alcohol and probably even worse, seen to be taking money for it.

I do think though that individuals, or an individual on behalf of a group of friends placing an order and then Dan Murphy's batching that order up for delivery because all of those people are going to be in the one place is definitely still BYO, and also just makes sense.  We just need a way to communicate this while making our purchases :)

**Comment by lukebrooker** [comment]
@DamonOehlman I was going to mention the spreadsheet idea, but had the same thoughts. It has worked well for me for car pooling in the past.

I'd be happy to look into our options. I did notice it was free delivery for "Metro" areas, not sure what Springbrook is considered. Even if considered regional, it should only be a small extra fee.

**Comment by lukebrooker** [comment]
So… there isn't a way to do multiple separate orders and get them delivered.

But, everyone could do a click and collect order and have a _single person_ go and pick up the orders. Everyone would just need to _nominate that specific person_ when they place their order.

I'd be happy to do this, except I won't have my own car available to get down as I was going to car pool.

**Comment by DamonOehlman** [comment]
Let me have a look at the bus lists, and see if I can identify some people that might be able to help.

**Comment by DamonOehlman** [comment]
OK, there are lot's of friendly faces of people that are catching the early bus from the airport.  I'll make contact with a few of them directly and see if someone would be willing to take on the responsibility of designated drinks courier.

**Comment by lukebrooker** [comment]
I went through the process and it looks pretty simple. We can even set a specific pickup date.

Here are the steps to be aware of:

![Choose a date for delivery](https://cloud.githubusercontent.com/assets/1305265/10960639/10e7b106-83d1-11e5-88d7-7577ccd4715d.jpg)

![screenshot-2015-11-05-15 19 25-v2](https://cloud.githubusercontent.com/assets/1305265/10960647/24d47f3c-83d1-11e5-824e-ceed0406b4e4.jpg)

Seems like we could tell everyone the date to set and the persons details to enter.

**Comment by DamonOehlman** [comment]
I've had a chat with @toolmantim who is on the first bus for transfer from the airport and he is happy to be a pick up contact for the orders.  So use the following details for info:

First name: Tim
Last name: Lucas
Mobile Number: 0428 906 980

The above mobile number is actually a twilio number that is all configured to put through information into a trello board so we can track the orders that way.  Saves giving out Tim Lucas' phone number to everyone and him getting a stream of SMS messages :)

**Comment by toolmantim** [comment]
:+1:

**Comment by lukebrooker** [comment]
Awesome. Good idea using Twilio.

I just remembered one other thing, is to make sure everyone chooses Robina as the store.

**Comment by DamonOehlman** [comment]
OK, Just went through the process end-to-end and it all feels pretty solid.  Here's what my confirmation screen looked like just before payment:

![dan-murphys-beer](https://cloud.githubusercontent.com/assets/609693/11019895/e4661d32-8661-11e5-9d93-b057a3bed9e3.png)

The only surprising part of the process is the confirmation email post purchase where they address me as Tim.  No real problem there - it's a fine name, just something I'll make people aware of when I do the email out about how to "buy your beer / cider / wine".

Additionally, I'm now considering how I can effectively share my beer.  I bought a carton because it's the most economical way to do it, but realistically the most I will drink over the weekend is half of that.  While we can't centralize ordering, I see no problem in creating some kind of spreadsheet (or something else) that allows us to flag that we have something available to share.  I'll have a think about that now and see what might work.
