### ISSUE TITLE
Airport Transfers

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#19]
Looking to get this locked in with the bus company in the next couple of days, please let me know if this looks good.  Primarily, I'm trying to cater for the bulk of people arriving at the airport on the Friday around or slightly after noon, but having some ability for people to get their later if they are going to try and work the Friday and then take a later flight to the Gold Coast.  Monday is the reverse which is why the smaller (28 seater) bus leaves earlier.

From a look at the times below, I think everything is looking pretty good, but perhaps we may need to push the early departure bus on the Monday a little earlier to try and get people to the airport at or around 10am.
### FROM Coolangatta Airport (Friday 20 November 2015)

BUS 1 - 48 seater

```
 14:00 - Pick up Airport
 14:45 - Pick up Varsity Lakes Train Station
~15:00 - Stop off at Dan Murphy's Robina for BYO collection
~16:30 - Koonjewarra
```

BUS 2 - 28 seater

```
 17:00 - Pick up Airport
 17:45 - Pick up Varsity Lakes Train Station
~18:00 - Stop off at Dan Murphy's Robina for BYO collection
~19:30 - Koonjewarra
```
### FROM Koonjewarre Retreat (Monday 23 November 2015)

BUS 1 - 28 Seater

```
 08:00 - Pick up Koonjewarra
~09:30 - Drop off Varsity Lakes Train Station
~10:00 - Drop off Coolangatta Airport
```

BUS 2 - 48 Seater

```
 10:30 - Pick up Koonjewarre
~12:00 - Drop off Varsity Lakes Train Station
~12:30 - Drop off Coolangatta Airport
```

cc #11

**Comment by DamonOehlman** [comment]
It's also worth noting that the estimated times at this stage, are based on very loose estimates made by me, but I'm hoping the bus company can also provide an estimate...

**Comment by web-goddess** [comment]
LGTM. Just booked my flights! :)

**Comment by ghost** [comment]
Looks rad. Lines up with the flights I had already booked. 👌
Thanks for organising this!

**Comment by bguiz** [comment]
+1

**Comment by DamonOehlman** [comment]
I've also just made the morning departure bus pickup from 8:00am which will give folks a little more time if they are trying to catch a Monday morning flight before noon.

**Comment by OphelieL** [comment]
Early departure on Monday = awesome.

**Comment by DamonOehlman** [comment]
Closing this, but if anyone has any feedback on the transfer times let me know and we can incorporate that for the next event :bus:
