### ISSUE TITLE
Expressions of Interest: Diversity

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#2]
Ensuring that the event is respectful to all parties attending, plus working with the Talks crew to help ensure that attendees have the opportunity to see "people like themselves" contributing to the knowledge sharing that makes CampJS awesome.

**Comment by tjstebbing** [comment]
Happy to help if you'd like me to.

**Comment by tjstebbing** [comment]
+1 for @AnnaGerber if she is interested :)

**Comment by AnnaGerber** [comment]
Sure, happy to help however I can

**Comment by MelissaKaulfuss** [comment]
chalk me up too – happy to be involved :)

**Comment by DamonOehlman** [comment]
Hey folks - looks like the first issue where we require some assistance and consultation is around the discussion we had is around whether to include alcohol or not as part of the ticket price.  There has been some existing good discussion on #12 but I think @timoxley hit the nail on the head asking for this to be something that is first and foremost tackled as a diversity issue.

To that end, I would like to:
1. Ensure that we have a good representation of people here to cover off issues of diversity that are going to come up in preparation and during CampJS VI.  I think this probably needs to include we have representation from what is considered the majority in developer circles.
2. Attempt to work out a process by which we can come to some kind of decision in an open, but not necessarily "everybody get's to have an opinion" way which is something that as @mipearson our current discussion is probably heading towards.

Does that sound reasonable and practical?

**Comment by tjstebbing** [comment]
I think there are some issues that might need to be discussed OTR. I know that's going to make people upset with regard to the open gov. model.  (not going to talk about them now).

Personally I think (and I said this in the alcohol thread) there were some fantastic points raised toward the end of the diversity panel about alcohol which were counter-points to the 'but we have a precedent and if we change it people may not come' argument.  ie: flip that around, 'who might not currently be coming because campjs is seen as a booze-up event?'  

I'm not anti-alcohol at all, however I do think we may have been skirting^h^h^hbreaking the law by not having someone with a responsible serving of alcohol accreditation. Especially after we become a NFP. Which is why I suggested making it someone else's problem (hire a bartender/bar).

The subsidization argument is a significant one.  I'm not a big drinker, I might have 1 or 2 ciders max, @timoxley mentioned that alcohol was a significant portion of the ticket price, why am I subsidizing someone else to drink?  

If I was from a religious background that prevented me from drinking, how might I feel about paying a % of my ticket price to facilitate something that I might be ethically against?

Just some things to consider.

**Comment by tjstebbing** [comment]
Actually on the point of openness and ticket prices, It would be good to start seeing post-camp breakdowns on what % of a ticket went to what cost (on the registration page maybe? at least for planning). Do we have this info from previous camps?

**Comment by DamonOehlman** [comment]
@pomke Good points, and yes, I'll put an item on my list to be able to provide a % cost of where your CampJS V ticket price went so that information can be "above the fold" and talked about.

**Comment by tjstebbing** [comment]
Some links :)
- https://modelviewculture.com/pieces/alcohol-and-inclusivity-planning-tech-events-with-non-alcoholic-options
- http://geekfeminism.wikia.com/wiki/Women-friendly_events#Alcohol 

And 

http://old.ryanfunduk.com/culture-of-exclusion/  which was specific to jsconf and their response:
http://www.voodootikigod.com/our-culture-of-change/

**Comment by MelissaKaulfuss** [comment]
I agree with all the above – I think making alcohol less of a focus is
better for people that don't drink or don't feel comfortable with it.
That said, it's hospitable to provide drinks and I for one drink them, I
feel like it encourages a nice social environment – is that bad?

One option is to not supply them – but then – I'd expect to see a cheaper
ticket price, and the camp bus swing past a bottle shop for interstate
travellers to purchase their supplies. This is what Railscamps used to do.

**Comment by AnnaGerber** [comment]
Focusing on the questions of process raised above:

The issue of the legality of supplying alcohol and whether we will be exempt from requiring a liquor permit if we become an association is not a diversity issue and I would suggest the group should get some legal advice on this. Note that if the group gets a community license in QLD then BYO alcohol is not permitted.

Things the diversity crew can do:
- gathering input from the community and reflecting on our own experiences at past events to summarise previous alcohol-related issues
- researching what other groups have done to address similar issues and providing a list of suggestions for creating a safe and welcoming environment at the next camp (thanks @pomke  for starting this already)
- providing advice on language used in promoting the event and on the webpage (in the past this language has been called out for being seen to encourage drinking culture)
- making sure everyone is aware that they may be minors present and providing guidelines for responsible consumption of alcohol and unacceptable behaviours like spiking drinks (maybe these could be linked from the code of conduct)

BTW I don't think different ticket types with armbands are a good idea at all.  It's awkward enough to be not drinking at events where just about everyone else is, without having to wear a visible sign (e.g. lack of an armband) to make it even more obvious that you are different.

**Comment by DamonOehlman** [comment]
Thanks @AnnaGerber - yeah, it's starting to sound more and more that from a legal, not ethical standpoint we may need to be seen to be supplying alcohol.  In trying to keep costs lean for this event, I'm really trying to manage outlay of such things for legal advice, etc.  I'll start another issue with my wrapped up thoughts.

**Comment by DamonOehlman** [comment]
Would be great to have a chat with you folks via skype, webrtc, etc sometime soon (or even all just hang out in a room on viewsource).  Keen to make sure we are doing all we can to make CampJS as welcoming as possible to all people :)
