### ISSUE TITLE
Coffee in the wee hours

### ISSUE THREAD

**Issue by MauriceButler** [campjs/campjs-vi#20]
Just wanted to check what the coffee situation will be outside the hours the barista being supplied by Lookahead Search / @G-face will be working.

(I am assuming we do not have a team of baristas working round the clock, if so problem solved...)

Possibly we still need the pod machines we have had in the past to get us addicts through until the baristas are back on deck?

Im not sure if they were "CampJS" owned or not.

**Comment by DamonOehlman** [comment]
Hmmm, good question Maurice.  I'm not sure.  If the pod machines were CampJS owned, then I think it makes sense to have those available as well.  If not I can probably organise to purchase one pod machine with a sufficient supply of pods to satiate those night caffeine cravings...

**Comment by G-face** [comment]
Hey @MauriceButler, official barista will be there 9.30am to 11.30am and 1.30pm to 3.30pm both days (so no barista coffee at midnight, I'm afraid). Pods sound cool though, if they're not around, we might be able to see if there's some filter options.. Let me know how you go.

**Comment by SomeoneWeird** [comment]
Perhaps we can get someone to courier a pod machine up if we reimburse them?

**Comment by DamonOehlman** [comment]
@G-face good point, I could pack my aeropress - I don't really use it here at home that much because I'm just not hipster enough... perfect for CampJS though :)

**Comment by MauriceButler** [comment]
Usually there are a number of aeropress and chemex brought by people for their own requirements.

@nigelr might know the story of the existing pod machines?

**Comment by DamonOehlman** [comment]
@MauriceButler yeah I heard through non-github channels that they might be stored at the venue.  Going to send David an email in the next couple of days about :allthethings: so I'll include a question on the pod machines also :)

**Comment by DamonOehlman** [comment]
I've confirmed that the pod machines we used at the last event have been stored at the venue and thus are available for us again.  We just need to source some pods for the event.  These were Aldi Espressi machines right?

Also, a question asked on view source re milk (milk steamer, etc - cc @damncabbage):

https://viewsource.slack.com/archives/linux/p1445825348000142

**Comment by nigelr** [comment]
@DamonOehlman they were woolworths machines...
We ordered extra milk which was delivered last time (unsure of how much)

**Comment by DamonOehlman** [comment]
@nigelr Thanks mate - that makes things nice and easy then.  Will look to do an online order with woolworths closer to the event date then :)
