### ISSUE TITLE
Sound equipment

### ISSUE THREAD

**Issue by rvagg** [campjs/campjs-vi#21]
@DamonOehlman has this been handled anywhere else yet? Do I need to make sure this happens?

Below is roughly the list we've used for the last two CampJS', from djwarehouse.com.au who service both locations for us. Delivery is more in VIC than in QLD hence the difference in totals at the bottom.

In the past 3 CampJS' I've taken care of sound gear and wine, splitting the expense across personal and NodeSource as a "sponsorship". I'm going to try and push them both through as NodeSource on a community stipend even though I think I've pushed the limits of that already. Given that it'll be close to $1k, can I get something more official for NodeSource in the way of sponsorship? A logo and shoutout or whatever we're giving to sponsors these days?

Here's the sound equipment list as it's evolved so far, please critique. The idea has been to have a primary setup for the main hall with two speakers and a desk, then have two more single speakers and desks available to make either another large setup or two single speaker + desk setup. In QLD we've split these two smaller ones across the cafeteria and the smaller breakout hall. Does anyone have any better suggestions on this?

Assuming I'll be there (not an absolute given at this stage although I have a ticket), I'll be bringing some extra gear—cables, mics and probably my mini desk if we want to record a NodeUp.

@DamonOehlman: let me know if I should go ahead and make this happen.

Labour
1 x DEL40 - Economy Residential Delivery (long range) @ $40.00: $40.00
1 x PIC40 - Economy Residential Pickup (long range) @ $40.00: $40.00

Microphones
3 x PG58 - Microphone With Switch 498 @ $10.00: $30.00

PA Mixers
3 x EPM6 - Soundcraft 6 Chan Mixing Desk 495 @ $20.00: $60.00

PA Speakers
4 x 615 - Jbl Prx 15inch Powered Speaker 258 @ $40.00: $160.00

Stands
4 x SPS - Speaker/Lighting Stand 101 @ $0.00: $0.00
4 x MS - Microphone Boom Stand 216 @ $10.00 $40.00

Last QLD CampJS: $387
Last VIC CampJS: $450

**Comment by DamonOehlman** [comment]
@rvagg I've gone and sourced a whole pile of stuff from a local hire place (marquee, etc), including some [sound gear](http://www.gcpartyhire.com.au/index.php/Packages/PA-Package/flypage.tpl.html) (3 complete sets).  While I have no idea of the quality I think they will probably do the job (small mackie's should be pretty reliable).  Knew you were super busy with node related things so just took care of it.

I can also bring a few bits of gear too, but if you are coming then I think bringing your small mixer with the intent of possibly recording a node up would be awesome.

With regards to the wine, more than happy for you / nodesource to source some bottles of wine, and a couple of other companies have offered to buy a case or two of beer in the current BYO environment also (Seed Digital - cc @mebinum).  More than happy to recognise companies that are doing this in some way through logo placement at the event and on the site also (actual size and placement TBD).

**Comment by rvagg** [comment]
ahhh, I hadn't tuned in to BYO being a thing this time, I realise it was discussed. I might just bring some of my personal stash to share then!

Sounds good on the sound gear front, you're killing it @DamonOehlman, don't push yourself so hard that you count yourself out of doing this ever again!
