### ISSUE TITLE
Wine

### ISSUE THREAD

**Issue by rvagg** [campjs/campjs-vi#22]
The last 3 (or is it 4?) CampJS' I've provided wine, the intention is to come a bit closer to meeting the needs of the wine snobs amongst us (obviously not actually meeting those needs, but getting closer than would otherwise happen if we just told a bottle shop to give us whatever's selling well). I've done 4 cases for each, there has been excess at a couple of events because of the red/white split. The current observation is that while in QLD we are happy drinking more white than when in VIC where it's colder and we gravitate heavily to the red (I brought home a case of white from the last CampJS). I think for this one we could probably get away with an even split between red and white .. or maybe slightly more red.

Has anything else been organised or planned for wine at this CampJS or should I go ahead and order some be delivered to Koonjawarree and try and get NodeSource to pay for it?

**Comment by rvagg** [comment]
I forgot to mention about glasses—we have some glasses at someone's house. Last I saw them was in QLD, we didn't have them in VIC but instead we got 4 dozen (I think) from the place down the road that we got other grog from and it didn't cost us any extra.

Does anyone know where the boxes of CampJS glasses are and if they can make it to Koonjawarree?

Alternatively, whoever is organising the beer etc. could you check with the supplier if they have wine glasses they can rent (or throw in) with our order?

**Comment by DamonOehlman** [comment]
Answered this mostly (I think) in #21 :)

Basically, with the BYO restriction this time around CampJS itself won't be supplying any alcohol (due to legal reasons, which we will look to resolve in the future as part of being an incorporated association), but companies and individuals are more than welcome to bring such things to share.  Happy to source glasses if required though.
