### ISSUE TITLE
International Visitors keen to hang around, need a place to crash :)

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#23]
Morning all - Have just been chatting to @juliangruber who will be coming from Germany and speaking at the event.  Julian is keen to possibly hang around for a couple of days after the event and check out the Gold Coast and/or Brisbane.  Just wondering if there's someone what might have a couch that he can crash on.

I've personally hung out with Julian and can vouch for him being a super nice guy :)

**Comment by KoryNunn** [comment]
We've got a spare room, if Julian doesn't mind the location.

**Comment by juliangruber** [comment]
Thank you for the offer @KoryNunn, but unfortunately I won't make it this year
