### ISSUE TITLE
Expressions of Interest: Sponsorship and Swag

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#4]
Our sponsors make a big difference to our event, and this is where a lot of effort is required.  If you are good at talking to companies and helping them support community events like CampJS - please get involved :)

**Comment by davidmason** [comment]
I am chasing up sponsorship from my employers. Looks good so far.

**Comment by AllyG** [comment]
Are the sponsorship packages basically the same as on the CampJS V Sponsorship doc? https://docs.google.com/document/d/1y6iQmHl0Cx-RGQeNGwcbpgs6b3gZ4YbV3Kbqz60KHT0/preview?pli=1

**Comment by DamonOehlman** [comment]
@AllyG I think those tiers mostly worked well.  I would be tempted to simplify it down to only have 2K, 4K and 8K tiers with us highlighting that we are happy to talk to people should the packs not suit their needs.  While we value all the help we get from our sponsors, we did end up with a lot of people just going for the 1K pack as that was the advertised lowest.  So I wonder if more people would have gone for the 2K pack if that was the lowest visible?

**Comment by SomeoneWeird** [comment]
That's quite possible, maybe we should remove the 1K pack and say that we would be happy to accept lower sponsorship packs too (but we just don't list them) ?

**Comment by DamonOehlman** [comment]
Yep with some wording about "we are happy to discuss smaller sponsorship packs for smaller companies and startups wishing to support CampJS" :)

**Comment by MauriceButler** [comment]
So this was mentioned off the cuff at work the other day but I can hopefully turn it into a real thing.

Can possibly get drinks sponsored by a "large liquor chain"

Is this something I should pursue or is there a standing supplier / relationship that needs to / should be honored? 

If I can pull it off could assist with sponsorship / budget pressure as I assume (possible incorrectly) drinks are a large part of the costs?

**Comment by DamonOehlman** [comment]
Drinks are definitely a part of the cost (I think around 3K - which is not as much as I thought they would be).  I tried a similar thing though with a supplier Lions Brewing and found they were actually limited in what they were allowed to sponsor, though an alcohol retailer might be able to do something :)

Basically every bit of sponsorship takes pressure off the bottom line, but I think we should look to ensure that the basics are covered through ticket sales (with fewer special pricing things) and nice to haves through sponsorship, such that in the event that we ended up with zero sponsorship we would still have an event and not someone losing money...

**Comment by hughsk** [comment]
You might want to contact Coopers, back when we were organising exhibitions in university they were supposedly always very willing to chip in with drinks sponsorship :)

**Comment by G-face** [comment]
Hey! Lookahead Search would be interested in sponsoring coffee :) Is that still available / an option?

**Comment by DamonOehlman** [comment]
Absolutely Georgina!  I've done some preliminary investigations on some potential mobile barista's that could probably get to Koonjewarre.  Did you want me to do some further checking and put you guys in touch?  In many ways it might be simpler if you liase with them directly as you'll be able to claim the GST input credits etc :)

Thanks for the interest!

**Comment by G-face** [comment]
Hey Damon, happy to speak directly with the baristas. Perhaps ping me an email introduction g@lookahead.com.au and I'll take it from there :)

Thanks!

**Comment by DamonOehlman** [comment]
@davidmason would you mind chasing up your people at some stage please?  If Red Hat are keen I'm really interested in them coming on as a transport sponsor (i.e. covering the bus hire, or at least subsidising it).  Covering the full cost would give them "naming sponsor" rights - it would be the Red Hat bus to and from camp :)

**Comment by davidmason** [comment]
@DamonOehlman looking into it.

**Comment by DamonOehlman** [comment]
Thanks David - also if you see @lukebrooker around the halls of Red Hat, remind him he should come along too :)

**Comment by lukebrooker** [comment]
@DamonOehlman Don't worry I'll be there :wink: Just haven't got around to getting the ticket yet.

**Comment by DamonOehlman** [comment]
@davidmason Just a heads up that I've also pinged Steven Pousty who I know from my days doing geo stuff.  If you haven't got much traction yet, I'll put a proposal together around the transport and send it through Steve.  I've outlined at a high level what I was thinking re transport and he thinks that it can probably work...
