### ISSUE TITLE
Expressions of Interest: Logistics

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#5]
All the stuff the people like me would forget.  This will quite possibly split into multiple groups (networking, transport, food, etc) but for now let's just get some names down if you feel you can help out in this way.

**Comment by SomeoneWeird** [comment]
_raises hand_

**Comment by MauriceButler** [comment]
Happy to help with this too, can probably do some gofering etc.

**Comment by MauriceButler** [comment]
Am I too forward in assume you will be available and willing to help by applying your amazing skills with networking / internet / all the magic no one knows happens behind the scenes @geoffreyd ?

@eugeneware possibly aswell ?

**Comment by SomeoneWeird** [comment]
Yeah, myself, mp, deoxxa & eugene have managed the intranet/internet for the last few campjs's, I'm sure whoever goes to the next one can help too.

**Comment by MauriceButler** [comment]
Very good. I will leave it in your collective, capable hands then.

**Comment by DamonOehlman** [comment]
I might close this issue and kick off the three separate threads as I originally mentioned.  Sounds like networking is well thought about, but I do think we need to have some discussion around transport (especially buses to and from the airport).
