### ISSUE TITLE
Current Status: Where are we at? Do we even have a venue?

### ISSUE THREAD

**Issue by MauriceButler** [campjs/campjs-vi#6]
Sooo things have been quiet for a while, can we do a status update and maybe remind us all involved that this is a thing that needs our attention.

First thing would be do we still have a venue? 

I believe Koonjewarre were going to give us one more event? (@nigelr to confirm maybe?)

Does that have a time out? its getting close to the end of the year so not much time to organise it for 2015.

**Comment by SomeoneWeird** [comment]
@DamonOehlman

**Comment by nigelr** [comment]
@MauriceButler Koonjewarrie are always an option (just call them and find dates).. I had heard that Sydney was the next camp.

**Comment by MauriceButler** [comment]
Thats good then.

Maybe my mind made that up in a haze that we could not use them any more... I have no idea why...

I also though the next camp was QLD, this repos README says CampJS VI (to be hosted in Springbrook, QLD) but again maybe that has changed?

More reasons us like-minded people should get our heads together and confirm what we are trying to do.

**Comment by DamonOehlman** [comment]
My understanding is that @timoxley had already secured the venue for as he said "one. last. campjs."

Date TBC though. @timoxley ?

**Comment by DamonOehlman** [comment]
And yes @MauriceButler was just thinking this the other day...

**Comment by KoryNunn** [comment]
AFAIK the Koonjewarrie venue is changing owners, and we have the chance to secure one more CampJS there before needing to renegotiate (@timoxley can confirm/invalidate)

There are a few options available for a venue if we run out of time, but obviously if Koonjewarrie is available.. Some options may include a Brisbane CBD venue (don't worry, still dorm-style), which I'd like to probe interest for.

I think the key to this happening this year is for someone to take the reins, at least so far as to just allocate tasks to multiple people. I'd be happy to help out where I can but I don't have the time to do all the work Tim would usually do (also I'm horrible at organising myself let alone >1 people).

**Comment by SomeoneWeird** [comment]
Yeah, the owners delayed their handover for CampJS to host their next event there apparently.

**Comment by DamonOehlman** [comment]
Absolutely, I'm certainly happy to help keep things moving along, but like Kory organising stuff isn't my strong suit.  I'd suggest that as long as we all keep each other honest we should be able to pull it off without too much stress.

Venue is definitely key though and I think @timoxley is still the only one with that information, though I've been meaning to get the information out of him (i.e. ask).  I guess here is as good a place as any with our new open-governance model :smile:

**Comment by DamonOehlman** [comment]
So on that note, big thanks to @MauriceButler for opening this issue :cake:

**Comment by SomeoneWeird** [comment]
I guess the first thing that needs doing is deciding a date, which is also pursuant to venue availability.

**Comment by DamonOehlman** [comment]
My thinking is that the date is already set (based on a conversation Tim has had with current Koonjewarrie owners), and just relies on Tim sharing it.  I might be wrong though.

**Comment by todthomson** [comment]
> Current Status: Where are we at? Do we even have a venue?

Do we have a date yet? It would be super cool to have a date so we can organise leave for the Friday/Monday :+1: :sunglasses:

**Comment by DamonOehlman** [comment]
@nigelr Would you mind giving Koonjewarrie a call seeing as you have had previous dealings with them and see if they can catch you up on what @timoxley and they talked through.  I'm guessing Tim is either AFK or neck deep in some project work at the moment...

**Comment by nigelr** [comment]
@damonOehlman could be other things!
![11822417_10207259559552726_4518498951811739234_n](https://cloud.githubusercontent.com/assets/14952/9075899/5781e6b0-3b5e-11e5-9305-0fa5763d2013.jpg)

**Comment by SomeoneWeird** [comment]
Yay! Congrats @timoxley :)

**Comment by timoxley** [comment]
Sorry, I was travelling. We have the Koonjewarre venue booked in for the weekend of the 20th of November. I've emailed you their contact details Damon.

**Comment by DamonOehlman** [comment]
Woot - congrats Tim :)

Disregard my last email response...

I thought you were actually getting married in October.

Looking super sharp!

**Comment by timoxley** [comment]
@DamonOehlman I am in fact getting married in November. This photo is just from the pre-wedding photo shoot.

**Comment by DamonOehlman** [comment]
Ah, :camera:

Anyway, I've added the date to the README and which includes a link to the Lanyrd event details.  I'll drop a note on #1 to see if folks would like to use Lanyrd for getting proposals for talks in or something else.  I'll also try and work out how to add other people to the lanyrd event so we can distribute managing that also.

**Comment by MauriceButler** [comment]
Woot! Progress and a date! 

Next step speakers and flog tickets?

Making this a thing maybe? http://vi.campjs.com/

**Comment by SomeoneWeird** [comment]
We can do that! I think Tim is the only one with DNS access for the domain, though.

**Comment by timoxley** [comment]
I can change DNS, but I think @geoffreyd or @nigelr may need to be the ones to add other owners:

![image](https://cloud.githubusercontent.com/assets/43438/9078290/55c178c0-3b01-11e5-8e5d-bb8eb187355e.png)

**Comment by geoffreyd** [comment]
@timoxley Who do you want added to DNS?

**Comment by KoryNunn** [comment]
@geoffreyd http://vi.campjs.com/ should point somewhere

**Comment by SomeoneWeird** [comment]
@geoffreyd potentially damon and myself?

**Comment by geoffreyd** [comment]
@SomeoneWeird OK, going to need some emails to send invites to.

**Comment by DamonOehlman** [comment]
@geoffreyd mine is damon.oehlman@gmail.com though I'm sure @SomeoneWeird will be a better long term contact for doing this kind of thing :)

**Comment by SomeoneWeird** [comment]
adam@boxxen.org

**Comment by geoffreyd** [comment]
OK, added ... I've also pointed vi.campjs.com -> CNAME -> campjs.github.io as the previous ones are.

**Comment by SomeoneWeird** [comment]
:tada:

**Comment by MauriceButler** [comment]
OK 6 days without anything visible going on im going to poke again.

***poke**

Next steps (possibly deserve thieir own issues?)
1. Website for vi.campjs.com to point at.
2. Ticket Sales

Here is my effort happy for this to be used or for someone to make some improvements. 

``` html
<html>
<head>
    <title>CampJS VI</title>
</head>
<body>
    <h1>CampJS VI</h1>

    <p>IT WILL BE GOOD</p>

    <p>YOU SHOULD COME<p>

    <p>BUY TICKETS <a href="totestickets.com">HERE</a><p>
</body>
</html>
```

Also ticket sales. Do we have an existing account / payment gateway? I think PIN was used last time?

**Comment by SomeoneWeird** [comment]
Last ticket sales used Tito. We should probably just fork the CampJS V website for VI - path of least resistance.

**Comment by DamonOehlman** [comment]
@MauriceButler thanks for the weekly prod. Keep it up.  Also, some of your best work there with the new site :)

@SomeoneWeird yep - ti.to was excellent and it should be a no brainer to create tickets for the next event there.  And forking the previous site is probably a good place to start, though surely amongst our number is someone with a creative urge to do something awesome...  if not, yes, let's just fork.

My opinion of what is the next most pressing thing is to try and establish some kind of budget for the camp.  To that end, I'll open a new issue on that topic and reference this issue.

**Comment by SomeoneWeird** [comment]
Going to make a start on the new website, will just import the campjs5 one and start from there - need to get something up ASAP, we can change it after if need be.

**Comment by DamonOehlman** [comment]
Sounds good.  I'd go with the tickets on sale soon angle :)

**Comment by SomeoneWeird** [comment]
http://vi.campjs.com/

**Comment by MauriceButler** [comment]
much better than the 404 :+1:

**Comment by MauriceButler** [comment]
I am thinking this issue can probably be closed now as I believe the touch points have been done or broken out into other issues.
