### ISSUE TITLE
I'd love to hear a talk on <INSERT TOPIC HERE>

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#8]
If you've attended or are thinking about attending [November's CampJS](http://vi.campjs.com/) please let us know what kind of technical (or non-technical) talks you'd like to hear in a comment below :)

**Comment by bevacqua** [comment]
Anything on: web audio, webrtc, service workers, webgl, webvr, mad science _(p2p, bitcoin, crypto, sec)_, http/2

Just throwing interesting newish things out there

**Comment by AnnaGerber** [comment]
Techical:
- Building cross-platform apps using Electron (or similar)
- Hands-on with Workers (workshop)

Fun:
- Web MIDI API
- Modding /  doing other cool stuff with Minecraft with JS

**Comment by yoshuawuyts** [comment]
- audio
- graphics
- robotics (revenge of the node{copters,boats}?)
- p2p

Combine subjects for extra points. Add MVC tooling to get points deducted.

**Comment by MauriceButler** [comment]
+1 for Hands-on with Workers (workshop) (@ashkyd maybe ?)

**Comment by johnlombardo-dev** [comment]
Seconding @AnnaGerber's technical suggestions.
- Electron, Ionic
- Workers, Lambda

**Comment by MauriceButler** [comment]
A good non technical topic that I have seen a many others enjoyed at other conferences was an explanation of contract law, worded in such a way that us non legal experts can understand. 

I believe something along those lines would be a good addition as there are usually a number of freelances attending.

Ill see if I can track down the speakers.

**Comment by timoxley** [comment]
@MauriceButler A good candidate for such a presentation would be https://twitter.com/melsherrin who I believe is a lawyer and has been to CampJS in the past.

**Comment by timoxley** [comment]
Here's an idea for everyone who has suggested a topic:

@bevacqua, @AnnaGerber, @yoshuawuyts, @MauriceButler, @programbo

You – could – now see it as your responsibility to find & nominate candidates to deliver the content you suggested or… **consider just presenting the topic yourself**, whether you know the topic today or not. Signing yourself up to give a presentation is a great way to force yourself to learn a topic.

**Comment by MauriceButler** [comment]
I have also been chatting with a couple of other legal minds who seem keen to be involved aswell https://twitter.com/Idealaw/status/633508471036448768

Also Ill try to lock @ashkyd in tonight at BrisJS drinks.

**Comment by SomeoneWeird** [comment]
That would be awesome

**Comment by voltrevo** [comment]
I know it's early days, but I'd love to hear about [WebAssembly](https://github.com/WebAssembly).

**Comment by DamonOehlman** [comment]
:100: for web assembly - a very interesting topic.  @voltrevo any interest in doing some investigations yourself and presenting a talk on it?

**Comment by pauljt** [comment]
So I asked about Web Assembly, but the response was that it might be a little early, with the standard still being defined and no representative prototypes yet. (But don't let me dampen any enthusiasm :) 

What about WebVR? Anyone interested in that? (e.g. the stuff at http://mozvr.com/ ) I might be able to find someone to present on that, or if not there are lots of materials available that someone could present on.

**Comment by DamonOehlman** [comment]
@pauljt thanks for asking around re webassembly.  If it is still very much in the forming/storming phase then it probably is best left for an event sometime in the future...

The WebVR stuff does look pretty interesting so if there is someone within the Mozilla family who is keen to come out and present on it, I think we'd definitely be interested.

**Comment by garrows** [comment]
I'd love to hear a talk on marketing your shiny new thing.

**Comment by DamonOehlman** [comment]
@garrows That's a good idea.  If @eugeneware can make this CampJS maybe he'd be up for it - no pressure though Eugene :)
